# Generated by Django 5.2.12 on 2026-03-29 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0002_alter_fields'),
        ('expense', '0002_alter_password'),
    ]

    operations = [
    ]
