# Generated by Django 5.2.12 on 2026-03-29 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0003_merge_0002_alter_fields_0002_alter_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='ExpenseCost',
            field=models.CharField(max_length=100),
        ),
    ]
