# Generated by Django 5.2.12 on 2026-04-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense', '0004_alter_expense_expensecost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
